//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hands_on_Programming_5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VolunteerDBEntities : DbContext
    {
        public VolunteerDBEntities()
            : base("name=VolunteerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lib_regions> lib_regions { get; set; }
        public virtual DbSet<lib_sex> lib_sex { get; set; }
        public virtual DbSet<VolunteerList> VolunteerLists { get; set; }
    }
}
